// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbPos
    {
        [DataMember(Name = "rotation")]
        public float Rotation;
        [DataMember(Name = "translation")]
        public DbVec2 Translation;

        public DbPos(
            float Rotation,
            DbVec2 Translation
        )
        {
            this.Rotation = Rotation;
            this.Translation = Translation;
        }

        public DbPos()
        {
            this.Translation = new();
        }
    }
}
