// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePhysicsHandler(ReducerEventContext ctx, UpdatePhysicsTimer timer);
        public event UpdatePhysicsHandler? OnUpdatePhysics;

        public void UpdatePhysics(UpdatePhysicsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.UpdatePhysics(timer), this.SetCallReducerFlags.UpdatePhysicsFlags);
        }

        public bool InvokeUpdatePhysics(ReducerEventContext ctx, Reducer.UpdatePhysics args)
        {
            if (OnUpdatePhysics == null) return false;
            OnUpdatePhysics(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePhysics : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public UpdatePhysicsTimer Timer;

            public UpdatePhysics(UpdatePhysicsTimer Timer)
            {
                this.Timer = Timer;
            }

            public UpdatePhysics()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "update_physics";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePhysicsFlags;
        public void UpdatePhysics(CallReducerFlags flags) => UpdatePhysicsFlags = flags;
    }
}
