// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BumperHandle : RemoteTableHandle<EventContext, Bumper>
        {
            protected override string RemoteTableName => "bumper";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Bumper row) => row.Id;

                public IdUniqueIndex(BumperHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BumperHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Bumper row) => row.Id;
        }

        public readonly BumperHandle Bumper;
    }
}
